### ISSUE TITLE
ManiphestExcelDefaultIncludeCustomFieldsFormat.php not working

### ISSUE THREAD

**Issue by talelk** [neandrake/phab-utils#1] opened 2016-03-02 17:30 UTC
Hi,

i'm getting this error message when trying to export:

> > > UNRECOVERABLE FATAL ERROR <<<

Call to undefined method PhabricatorProjectColumnPositionQuery::needColumns()

/opt/phabricator/phabricator/src/extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php:180

┻━┻ ︵ ¯_(ツ)_/¯ ︵ ┻━┻

**Comment by neandrake** [comment] 2016-03-02 19:31
OK I'm seeing the same error. I suspect a recent change in Phabricator (past month or so) caused an incompatibility. I'll try to look into this in the near future. For the moment my need for this extension has subsided so it hasn't been a priority for me lately.

**Comment by neandrake** [comment] 2016-03-04 05:48
Looks like this was caused by this recent change to Phabricator (early February):
https://secure.phabricator.com/D15177

I may have time this weekend to investigate a solution.

**Comment by neandrake** [comment] 2016-04-05 03:13
This should be fixed by d9e8c1cbd86513dcb208792c80d6687ced070deb

I'm doing some additional testing now.

**Comment by neandrake** [comment] 2016-04-05 03:46
OK, this looks good, with the last few changes added.

**Closed as completed by neandrake** 2016-04-05 03:46 UTC
